all: prob1 prob2 prob3 prob4

prob1:	cscd340Lab8prob1.c
	gcc -g cscd340Lab8prob1.c -l pthread -o prob1

prob2:	cscd340Lab8prob2.c
	gcc -g cscd340Lab8prob2.c -l pthread -o prob2

prob3:	cscd340Lab8prob3.c
	gcc -g cscd340Lab8prob3.c -l pthread -o prob3

prob4:	cscd340Lab8prob4.c
	gcc -g cscd340Lab8prob4.c -l pthread -o prob4

clean:
	rm prob1
	rm prob2
	rm prob3
	rm prob4
